# Generated by Django 5.2 on 2025-04-17 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('type_facture', models.CharField(choices=[('facture', 'Facture'), ('proforma', 'Proforma')], default='facture', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('payee', 'Payée')], default='brouillon', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('remise_globale_type', models.CharField(choices=[('aucune', 'Aucune'), ('pourcentage', '%'), ('montant', 'Montant fixe')], default='aucune', max_length=15)),
                ('remise_globale_valeur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise_type', models.CharField(choices=[('aucune', 'Aucune'), ('pourcentage', '%'), ('montant', 'Montant fixe')], default='aucune', max_length=15)),
                ('remise_valeur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='factures.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
    ]
