# Generated by Django 5.2.5 on 2025-08-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignefacture',
            name='type_remise',
            field=models.CharField(choices=[('aucune', 'Aucune remise'), ('pourcentage', 'Pourcentage'), ('montant', 'Montant fixe')], default='aucune', max_length=20),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='valeur_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
