# Generated by Django 5.2 on 2025-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_alter_facture_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
    ]
