# Generated by Django 5.2.5 on 2025-08-29

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('produits', '0001_initial'),
        ('factures', '0002_lignefacture_type_remise_lignefacture_valeur_remise'),
    ]

    operations = [
        # Garde l'ordre pour éviter les surprises
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date', '-id']},
        ),

        # ✅ Renommages (préservent les valeurs existantes)
        migrations.RenameField(
            model_name='lignefacture',
            old_name='valeur_remise',
            new_name='remise_valeur',
        ),
        migrations.RenameField(
            model_name='lignefacture',
            old_name='type_remise',
            new_name='remise_type',
        ),

        # ✅ Nouveaux champs sur Facture
        migrations.AddField(
            model_name='facture',
            name='objet',
            field=models.CharField(max_length=255, blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='tva',
            field=models.DecimalField(max_digits=5, decimal_places=2, default=Decimal('18.00')),
        ),
        migrations.AddField(
            model_name='facture',
            name='remise_globale_type',
            field=models.CharField(
                max_length=20,
                choices=[('aucune', 'Aucune remise'), ('pourcentage', 'Pourcentage'), ('montant', 'Montant fixe')],
                default='aucune'
            ),
        ),
        migrations.AddField(
            model_name='facture',
            name='remise_globale_valeur',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00')),
        ),
        migrations.AddField(
            model_name='facture',
            name='frais_livraison',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00')),
        ),

        # ✅ Harmonisation (si ton models.py a été ajusté ainsi)
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(
                to='clients.client',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='factures',
            ),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_document',
            field=models.CharField(
                max_length=10,
                choices=[('facture', 'Facture'), ('proforma', 'Proforma')],
                default='facture',
            ),
        ),
    ]
