# Generated by Django 5.2.5 on 2025-09-03 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_alter_facture_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='est_convertie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facture',
            name='source_proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='factures.facture'),
        ),
        migrations.CreateModel(
            name='SequenceNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('type_document', models.CharField(choices=[('facture', 'Facture'), ('proforma', 'Proforma')], max_length=10)),
                ('prochain', models.PositiveIntegerField(default=1)),
            ],
            options={
                'unique_together': {('annee', 'type_document')},
            },
        ),
    ]
