# Generated by Django 5.2.5 on 2025-09-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_facture_est_convertie_facture_source_proforma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyée', 'Envoyée'), ('payée', 'Payée'), ('convertie', 'Convertie')], default='brouillon', max_length=20),
        ),
    ]
