# Generated by Django 5.2 on 2025-04-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_alter_facture_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignefacture',
            name='remise_type',
        ),
        migrations.RemoveField(
            model_name='lignefacture',
            name='remise_valeur',
        ),
    ]
