# Generated by Django 5.2.5 on 2025-09-04 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_alter_facture_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='est_convertie',
        ),
        migrations.AlterField(
            model_name='facture',
            name='source_proforma',
            field=models.OneToOneField(blank=True, limit_choices_to={'type_document': 'proforma'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture_cible', to='factures.facture'),
        ),
    ]
