# Generated by Django 5.2 on 2025-05-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_remove_lignefacture_remise_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='objet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
