# Generated by Django 5.2.5 on 2025-09-04 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0006_remove_facture_est_convertie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='est_convertie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facture',
            name='source_proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_issues', to='factures.facture'),
        ),
    ]
