# Generated by Django 5.2.5 on 2025-09-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
        ('factures', '0007_facture_est_convertie_alter_facture_source_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='entreprises.entreprise'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='source_proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture_generee', to='factures.facture'),
        ),
    ]
