# Generated by Django 5.2.5 on 2025-09-05 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
        ('factures', '0008_facture_entreprise_alter_facture_source_proforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='entreprises.entreprise'),
        ),
    ]
