# Generated by Django 5.2.5 on 2025-09-10 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembreEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('staff', 'Utilisateur (écriture)'), ('lecture', 'Lecture seule')], default='staff', max_length=20)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprises.entreprise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'entreprise')},
            },
        ),
        migrations.AddField(
            model_name='entreprise',
            name='utilisateurs',
            field=models.ManyToManyField(related_name='entreprises', through='entreprises.MembreEntreprise', to=settings.AUTH_USER_MODEL),
        ),
    ]
