# Generated by Django 5.2.5 on 2025-09-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0002_membreentreprise_entreprise_utilisateurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='membreentreprise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
