# Generated by Django 5.2 on 2025-04-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('remise_type', models.CharField(choices=[('aucune', 'Aucune'), ('pourcentage', '%'), ('montant', 'Montant fixe')], default='aucune', max_length=15)),
                ('remise_valeur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
