# Generated by Django 5.2.5 on 2025-08-28 15:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('type_remise', models.CharField(choices=[('aucune', 'Aucune remise'), ('pourcentage', 'Pourcentage'), ('montant', 'Montant fixe')], default='aucune', max_length=20)),
                ('valeur_remise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
    ]
