# Generated by Django 5.2.5 on 2025-09-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
        ('produits', '0002_produit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='entreprises.entreprise'),
        ),
    ]
