# Generated by Django 5.2.5 on 2025-09-05 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
        ('produits', '0003_produit_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='entreprises.entreprise'),
        ),
    ]
